"""
    Fast

    FastAPI example with GitHub Action to generate client code.  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


import unittest

import fastapi_gh
from fastapi_gh.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_read_item(self):
        """Test case for read_item

        Read Item  # noqa: E501
        """
        pass

    def test_read_root(self):
        """Test case for read_root

        Read Root  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
