# flake8: noqa

"""
    Fast

    FastAPI example with GitHub Action to generate client code.  # noqa: E501

    The version of the OpenAPI document: 1
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from fastapi_gh.api_client import ApiClient

# import Configuration
from fastapi_gh.configuration import Configuration

# import exceptions
from fastapi_gh.exceptions import OpenApiException
from fastapi_gh.exceptions import ApiAttributeError
from fastapi_gh.exceptions import ApiTypeError
from fastapi_gh.exceptions import ApiValueError
from fastapi_gh.exceptions import ApiKeyError
from fastapi_gh.exceptions import ApiException
